### ISSUE TITLE
Specification for conjunction calculator

### ISSUE THREAD

**Issue by Aljutor** [DevHeap/collatz_conjecture#13]
We need minimal specification for our implementation of collatz conjunction calculator, especially in edge cases like negative numbers. We need proper rules of behaviour.  Result of this issue will be used to crate proper test suite.

**Comment by ghost** [comment]
How about this one:

Let us consider five values we need to show for every number in a line:
* Seed
* Path length
* Highest number in path
* Average number in path
* Calculation time

Let us consider the values above for four cases of seeds:
* Positive numbers
* n=1
* n=0
* Negative numbers

**Positive numbers**
* _Path length_ is number of numbers occuring until the first occurence of 1 in the sequence, including 1 and initial number
* _Highest number_ is the highest number occuring in a path
* _Average number_ is average of all numbers occuring until the first occurence of 1 in the sequence, including 1 and initial number
* _Calculation time_ is elapsed time between initial number being put into the calculation function and getting 1 (either way)

**Note:** the terms _'sequence'_ and _'path'_ are used interchangeably, as well as the terms _'seed'_ and _'initial number'_.

**The seed that equals 1:**
* _Path length_ = 1
* _Hightest number_ = 1
* _Average number_ = 1
* _Calculation time_ = 0

**The seed that equals 0:**
* _Path length_ = Infinity
* _Highest number_ = 0
* _Average number_ = 0
* _Calculation time_ = 0

**Negative numbers:**
Perform required operations on the sequence until you run into -1, -5 or -17.
* Got -1:
  * _Highest number_ = -1
  * _Average number_ = -1.5
* Got -5:
  * _Highest number_ = -5
  * _Average number_ = -11.2
* Got -17:
  * _Highest number_ = -17
  * _Average number_ = -90.0(5)
* _Path length_ = Infinity
* _Calculation time_ is elapsed time between initial number being put into the calculation function and getting -1, -5 or -17 respectively (either way)

**Note:** by _'either way'_ it is meant that the sequence may be partially or fully retrieved from the cache instead of being calculated from scratch. In this case, the moment of retrieval is considered to be the final point in time for recording the calculation time.

**Note:** averages specified for the case of negative numbers are averages for known negative number Collatz cycles that include -1, -5 and -17 respectively, as since paths for negative numbers are considered infinite, the head of a given path does not matter.
